# Generated by Django 5.2.8 on 2026-01-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ManyToManyField(blank=True, to='demo.company'),
        ),
    ]
