# Generated by Django 5.2.8 on 2026-01-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defualt.jpeg', null=True, upload_to=''),
        ),
    ]
