# Generated by Django 5.2.8 on 2026-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('carbonated', 'Carbonated Drinks'), ('juice', 'Natural Juices'), ('water', 'Bottled Water'), ('energy', 'Energy Drinks')], max_length=200, null=True),
        ),
    ]
